 platform :ios, '8.0'

target 'LWGInterviewDemo' do
        pod 'AFNetworking','~>3.1.0'
        pod 'MJExtension', '~> 3.0.8'
        pod 'SDWebImage', '~> 3.7.3'
        pod 'Masonry', '~> 1.0.1'
        pod 'MJRefresh'
end
